2024-12-23 04:00:16,873 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f629b65fd30>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2024-12-23 04:00:16,873 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f629b65fd30>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2024-12-31 17:00:37,448 - ERROR - ETL Process for Workly failed: APIError: [503]: The service is currently unavailable.
2025-01-01 14:00:03,309 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d0c11f9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-01-01 14:00:03,312 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d0c11f9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-01-04 10:00:50,906 - ERROR - ETL Process for Workly failed: APIError: [503]: The service is currently unavailable.
2025-01-05 10:00:40,055 - ERROR - ETL Process for Workly failed: APIError: [503]: The service is currently unavailable.
2025-01-06 02:00:14,023 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe97e217d60>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 02:00:14,024 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe97e217d60>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 03:00:14,281 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1910003940>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 03:00:14,291 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1910003940>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 07:00:14,179 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc42e7bb310>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 07:00:14,183 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc42e7bb310>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 14:00:12,805 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5e8e8b3550>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 14:00:12,815 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5e8e8b3550>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 17:00:13,076 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f785389f760>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 17:00:13,078 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f785389f760>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 19:00:12,954 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe8aa56b340>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 19:00:12,956 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe8aa56b340>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 20:00:14,081 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7feaf9aabd90>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-06 20:00:14,084 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7feaf9aabd90>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 03:00:15,066 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe68027fbb0>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 03:00:15,069 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe68027fbb0>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 04:00:16,361 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f866069b700>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 04:00:16,369 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f866069b700>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 05:00:13,578 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f6825737ca0>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 05:00:13,580 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f6825737ca0>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 06:00:12,804 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f2be3dfbb80>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 06:00:12,806 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f2be3dfbb80>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 07:00:04,760 - ERROR - Request failed for page 1: 402 Client Error: Payment Required for url: https://api.workly.uz/v1/reports/inouts?start_date=2024-11-01&page=1&per-page=50
2025-01-07 07:00:04,761 - ERROR - ETL Process for Workly failed: Failed to fetch inouts for page 1: 402 Client Error: Payment Required for url: https://api.workly.uz/v1/reports/inouts?start_date=2024-11-01&page=1&per-page=50
2025-01-07 08:00:14,501 - ERROR - Authentication request failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f98aabfbb50>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
2025-01-07 08:00:14,503 - ERROR - ETL Process for Workly failed: Authentication failed: HTTPSConnectionPool(host='api.workly.uz', port=443): Max retries exceeded with url: /v1/oauth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f98aabfbb50>: Failed to resolve 'api.workly.uz' ([Errno -2] Name or service not known)"))
